
trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: vs2017-win2016

variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.105'

- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool

- script: nbgv cloud
  displayName: Set Version

- task: DotNetCoreCLI@2
  inputs:
   
  displayName: Build  
  
- powershell: |
  
  displayName: Create packages
  
- task: DotNetCoreCLI@2
  inputs:
    command: test
 
  displayName: Run Tests
  
- task: PowerShell@2
  displayName: Authenticode Sign artifacts
  
   

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
 
